version: '3.8'
services:
  login-monitor:
    image: login-monitor
    command: python -u /app/monitor.py /app/auth.log webhook_weixin_token
    volumes:
      - /var/log/auth.log:/app/auth.log:ro
    restart: always